version: '3'
services:
  builder:
    image: node:16.18.0
    volumes:
      - ./:/var/www/html
    container_name: web_react
    command: >
      bash -c "cd /var/www/html && yarn install"

  web-react:
    depends_on:
      - builder
    image: nginx
    ports:
      - '8080:80'
    restart: always
    volumes:
      - ./config/nginx-custom.conf:/etc/nginx/conf.d/default.conf
      - ./config/mime.types:/etc/nginx/mime.types
      - ./build:/usr/share/nginx/html
    container_name: web-react
